CREATE DATABASE IF NOT EXISTS BANK;


CREATE TABLE IF NOT EXISTS BANK.USER
(
  ID         INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  LOGIN      VARCHAR(255)       NOT NULL UNIQUE,
  PASSWORD   VARCHAR(255)       NOT NULL,
  ADDRESS    VARCHAR(255)       NOT NULL,
  PHONE      VARCHAR(255)       NOT NULL UNIQUE,
  CREATED_AT BIGINT             NOT NULL
);

CREATE TABLE IF NOT EXISTS BANK.ACCOUNT
(
  ID         VARCHAR(36)        NOT NULL PRIMARY KEY,
  USER_ID    INT                NOT NULL,
  AMOUNT     DECIMAL(13,2)      NOT NULL,
  ACC_CODE   VARCHAR(255)       NOT NULL,
  CREATED_AT BIGINT             NOT NULL,
  DELETED_AT BIGINT             NULL,
  foreign key (USER_ID) references BANK.USER (ID)
);

CREATE TABLE IF NOT EXISTS BANK.OPERATIONLOG
(
  ID              INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  USER_ID         INT                NOT NULL,
  FROM_ACCOUNT_ID VARCHAR(36)        NULL,
  TO_ACCOUNT_ID   VARCHAR(36)        NOT NULL,
  ACC_CODE        VARCHAR(255)       NOT NULL,
  AMOUNT          DECIMAL(13,2)      NOT NULL,
  BEFORE_TRANSFER DECIMAL(13,2)      NOT NULL,
  AFTER_TRANSFER  DECIMAL(13,2)      NOT NULL,
  CREATED_AT      BIGINT             NOT NULL,
  foreign key (FROM_ACCOUNT_ID) references BANK.ACCOUNT (ID),
  foreign key (TO_ACCOUNT_ID) references BANK.ACCOUNT (ID),
  foreign key (USER_ID) references BANK.USER (ID)
);